#+TITLE: Source: Symphony

#+STARTUP: showall entitiespretty inlineimages
#+OPTIONS: toc:nil ^:nil

* About



* Scripts

** ~process-weekly-user-dump.rb~

Every week Symphony generates a big file (e.g. ~/sirsilogs/barcode.sysid.profile.affil.out-20180210~) that looks like this:

#+BEGIN_EXAMPLE
29007005111111|859199999|LAW|LAW|
29007013222222|872888888|EDUCATION|EDUCATION|
29007014333333|102777777|FACULTYX|CUPE3903|
29007015444444|100666666|STAFF|YUSA|
29007005555555|100555555|STAFF|YUSA|
29007016666666|100555555|STAFF|CPM|
#+END_EXAMPLE

That needs to be converted into CSV to be usable, which is what this script does.  It picks apart the fields (user_barcode, cyin, profile, affiliation) and outputs CSV.

It can be run on a specific file, or, if there is no argument, it runs on the most recent one.

The output is written to ~${DASHYUL_DATA}/symphony/user-information-$YYYYMMDD.csv~, and a symlink is made so that ~${DASHYUL_DATA}/symphony/user-information.csv~ is a stable filename that always points to the most recent data.

Uses:

+ ~convert-symphony-user-dump.rb~

Crontab:

#+BEGIN_EXAMPLE
## User information (weekly)
0 9 * * Sat  ${DASHYUL_HOME}/symphony/scripts/process-weekly-user-dump.sh
#+END_EXAMPLE

** ~process-catalogue-dump.sh~

Crontab:

#+BEGIN_EXAMPLE
## Symphony (monthly)
0 11 2 * * ${DASHYUL_HOME}/symphony/scripts/process-catalogue-dump.sh &> /tmp/catalogue-dump.txt; ${DASHYUL_HOME}/symphony/scripts/make-detailed-transactions.sh &> /tmp/detailed-transactions.txt
#+END_EXAMPLE

** ~make-detailed-transactions.sh~

Uses:

+ ~parse-monthly-transactions-logs.rb~ (which requires ~command-codes.rb~ and ~data-codes.rb~)
+ ~make-detailed-transactions-stage-2.R~
+ ~make-detailed-transactions-stage-4.R~
+ ~make-detailed-transactions-stage-5.R~
+ ~make-detailed-transactions-stage-6.R~

Crontab:  goes with ~process-catalogue-dump.sh~ because it needs to run right after it.

** ~extract-catalogue-title-metadata.rb~

** ~extract-catalogue-item-details.rb~
